/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/badge.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("radix") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * badge example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx agent-ui add`.
 */

import type * as React from "react"

import { Badge } from "@/components/radix/ui/badge"

export function Preview(): React.JSX.Element {
  return (
    <div className="flex flex-wrap gap-2">
      <Badge>Default</Badge>
      <Badge variant="secondary">Secondary</Badge>
      <Badge variant="outline">Outline</Badge>
      <Badge variant="destructive">Destructive</Badge>
    </div>
  )
}

export const usage = `<Badge variant="secondary">Draft</Badge>`
