/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/kbd.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("radix") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * kbd example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx agent-ui add`.
 */

import type * as React from "react"

import { Kbd, KbdGroup } from "@/components/radix/ui/kbd"

export function Preview(): React.JSX.Element {
  return (
    <p className="flex items-center gap-1.5 text-sm text-muted-foreground">
      Press
      <KbdGroup>
        <Kbd>⌘</Kbd>
        <Kbd>K</Kbd>
      </KbdGroup>
      to search
    </p>
  )
}

export const usage = `<KbdGroup>
  <Kbd>⌘</Kbd>
  <Kbd>K</Kbd>
</KbdGroup>`
