/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/select.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("radix") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * select example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx agent-ui add`.
 */

import type * as React from "react"

import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/radix/ui/select"

export function Preview(): React.JSX.Element {
  return (
    <Select
      defaultValue="standard"
      agent={{ id: "preview-select", label: "Preview select" }}
    >
      <SelectTrigger className="w-48">
        <SelectValue placeholder="Shipping method" />
      </SelectTrigger>
      <SelectContent>
        <SelectItem value="standard">Standard</SelectItem>
        <SelectItem value="express">Express</SelectItem>
        <SelectItem value="overnight">Overnight</SelectItem>
      </SelectContent>
    </Select>
  )
}

export const usage = `<Select
  defaultValue="standard"
  agent={{ id: "shipping-method", label: "Shipping method" }}
>
  <SelectTrigger className="w-48">
    <SelectValue placeholder="Shipping method" />
  </SelectTrigger>
  <SelectContent>
    <SelectItem value="standard">Standard</SelectItem>
    <SelectItem value="express">Express</SelectItem>
  </SelectContent>
</Select>`
