/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/tabs.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("radix") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * tabs example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx duz-ui add`.
 */

import type * as React from "react"

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/radix/ui/tabs"

export function Preview(): React.JSX.Element {
  return (
    <Tabs
      defaultValue="account"
      agent={{ id: "preview-tabs", label: "Preview tabs" }}
    >
      <TabsList>
        <TabsTrigger value="account">Account</TabsTrigger>
        <TabsTrigger value="billing">Billing</TabsTrigger>
        <TabsTrigger value="team">Team</TabsTrigger>
      </TabsList>
      <TabsContent value="account">Account settings.</TabsContent>
      <TabsContent value="billing">Billing details.</TabsContent>
      <TabsContent value="team">Team members.</TabsContent>
    </Tabs>
  )
}

export const usage = `<Tabs
  defaultValue="account"
  agent={{ id: "settings-tabs", label: "Settings" }}
>
  <TabsList>
    <TabsTrigger value="account">Account</TabsTrigger>
    <TabsTrigger value="billing">Billing</TabsTrigger>
  </TabsList>
  <TabsContent value="account">…</TabsContent>
  <TabsContent value="billing">…</TabsContent>
</Tabs>`
