/**
 * Gallery registry reader.
 *
 * Two needs, two data sizes:
 *
 * - Navigation (sidebar, base switcher) needs every item's name, title,
 *   description, type, `agentUi` and `bases`. That is exactly what the
 *   registry build writes to `registry.json`, with no file contents, and it
 *   is needed on every page — so it is imported statically.
 * - The component page needs one full item document, which inlines the
 *   component's source. Those documents are loaded lazily through a
 *   non-eager `import.meta.glob`, so a page fetches only the document it
 *   renders instead of every component's source.
 *
 * The output is laid out per primitive base: base-independent items sit at
 * the registry root, base-specific components in a `<base>/` subdirectory.
 * Every base is addressable in the URL (`/components/:base/:name`), the way
 * shadcn does it: a component missing from a base simply has no page there,
 * rather than being greyed out or redirected to a default base.
 */

import indexJson from "../public/r/registry.json"

export interface GalleryItem {
  name: string
  /** Primitive base this item is built for; `null` for base-independent items. */
  base: string | null
  title: string
  description: string
  type: string
  dependencies: string[]
  registryDependencies: string[]
  files: { path: string; content: string; target: string }[]
  agentUi?: AgentUiMetadata
}

/** Shape of a registry item JSON file, which does not know its own base. */
type RegistryItemFile = Omit<GalleryItem, "base">

/** Agent-native metadata, identical in the index and the item documents. */
type AgentUiMetadata =
  | {
      capabilities: { kind: string; actions: string[] }[]
      status: "agent-native"
    }
  | { status: "presentation" }
  | { status: "explicit-semantics" }

/**
 * Navigation-level entry from `registry.json`: what the sidebar and the base
 * switcher need, with no file contents. `bases` is omitted for
 * base-independent items, whose single document every base carries.
 */
export interface GalleryIndexItem {
  name: string
  type: string
  title: string
  description: string
  bases?: string[]
  agentUi?: AgentUiMetadata
}

/** Human titles for the bases, keyed by registry directory name. */
export const BASE_TITLES: Record<string, string> = {
  base: "Base UI",
  radix: "Radix UI",
}

const REGISTRY_ROOT = "../public/r/"
const REGISTRY_INDEX = "registry.json"
const RUNTIME_ITEM = "agent-ui-runtime"

// The index is machine-generated by `packages/registry/build.ts`; its JSON
// types do not carry the literal unions, hence the boundary cast.
const RAW_ITEMS = (indexJson as unknown as { items: GalleryIndexItem[] }).items

// The index document is excluded from the glob: it is read statically above,
// and a lazy entry for it would only produce a chunk nothing ever loads.
const itemDocuments = import.meta.glob(
  ["../public/r/**/*.json", "!../public/r/registry.json"],
  { import: "default" },
) as Record<string, () => Promise<RegistryItemFile>>

/**
 * Bases present in the registry output, discovered from the index — never
 * hardcoded.
 */
export const BASES: string[] = [
  ...new Set(RAW_ITEMS.flatMap((item) => item.bases ?? [])),
].sort()

const ITEM_BY_NAME = new Map(RAW_ITEMS.map((item) => [item.name, item]))

/** The bases carrying the item; a base-independent item is carried by all. */
function carriedBy(item: GalleryIndexItem): string[] {
  return item.bases ?? BASES
}

/**
 * Every registry item in `base` except the runtime, sorted with agent-native
 * components first and then alphabetically by name.
 */
export function listItems(base: string): GalleryIndexItem[] {
  return RAW_ITEMS.filter((item) => item.name !== RUNTIME_ITEM && carriedBy(item).includes(base)).sort(
    (a, b) => {
      const aNative = a.agentUi?.status === "agent-native"
      const bNative = b.agentUi?.status === "agent-native"
      if (aNative !== bNative) return aNative ? -1 : 1
      return a.name.localeCompare(b.name)
    },
  )
}

export async function getItem(
  base: string,
  name: string,
): Promise<GalleryItem | undefined> {
  const entry = ITEM_BY_NAME.get(name)
  if (!entry || !carriedBy(entry).includes(base)) return undefined
  // A base-independent item's document sits at the registry root; a
  // base-specific one in `<base>/`.
  const path = entry.bases
    ? `${REGISTRY_ROOT}${base}/${name}.json`
    : `${REGISTRY_ROOT}${name}.json`
  const load = itemDocuments[path]
  if (!load) return undefined
  return { ...(await load()), base: entry.bases ? base : null }
}

/** The bases whose registry output actually contains this item. */
export function basesFor(name: string): string[] {
  const item = ITEM_BY_NAME.get(name)
  return item ? carriedBy(item) : []
}
