/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples and
 * app/content/examples/overrides/radix — do not edit. Change those sources
 * and re-run `pnpm sync:gallery`.
 *
 * One lazy loader per example for the radix base. Where a hand-written
 * override exists for this base it wins; every other entry points at the
 * generated copy of the shared source, whose import specifiers were
 * rewritten to this base's component tree. Resolution happened here, in the
 * generator — consumers call the loader and get both the preview and the
 * usage snippet from the one module.
 */

import type { Example } from "@/content/example"

export const EXAMPLES: Record<string, () => Promise<Example>> = {
  "accordion": () => import("@/content/examples/overrides/radix/accordion"),
  "alert": () => import("@/content/examples/.generated/radix/alert"),
  "alert-dialog": () => import("@/content/examples/overrides/radix/alert-dialog"),
  "aspect-ratio": () => import("@/content/examples/.generated/radix/aspect-ratio"),
  "attachment": () => import("@/content/examples/.generated/radix/attachment"),
  "avatar": () => import("@/content/examples/.generated/radix/avatar"),
  "badge": () => import("@/content/examples/.generated/radix/badge"),
  "breadcrumb": () => import("@/content/examples/.generated/radix/breadcrumb"),
  "button": () => import("@/content/examples/.generated/radix/button"),
  "button-group": () => import("@/content/examples/.generated/radix/button-group"),
  "calendar": () => import("@/content/examples/.generated/radix/calendar"),
  "card": () => import("@/content/examples/.generated/radix/card"),
  "carousel": () => import("@/content/examples/.generated/radix/carousel"),
  "chart": () => import("@/content/examples/.generated/radix/chart"),
  "checkbox": () => import("@/content/examples/.generated/radix/checkbox"),
  "collapsible": () => import("@/content/examples/overrides/radix/collapsible"),
  "command": () => import("@/content/examples/.generated/radix/command"),
  "data-table": () => import("@/content/examples/.generated/radix/data-table"),
  "dialog": () => import("@/content/examples/overrides/radix/dialog"),
  "direction": () => import("@/content/examples/overrides/radix/direction"),
  "dropdown-menu": () => import("@/content/examples/overrides/radix/dropdown-menu"),
  "empty": () => import("@/content/examples/.generated/radix/empty"),
  "field": () => import("@/content/examples/.generated/radix/field"),
  "hover-card": () => import("@/content/examples/overrides/radix/hover-card"),
  "input": () => import("@/content/examples/.generated/radix/input"),
  "input-group": () => import("@/content/examples/.generated/radix/input-group"),
  "input-otp": () => import("@/content/examples/overrides/radix/input-otp"),
  "item": () => import("@/content/examples/.generated/radix/item"),
  "kbd": () => import("@/content/examples/.generated/radix/kbd"),
  "label": () => import("@/content/examples/.generated/radix/label"),
  "native-select": () => import("@/content/examples/.generated/radix/native-select"),
  "navigation-menu": () => import("@/content/examples/.generated/radix/navigation-menu"),
  "pagination": () => import("@/content/examples/.generated/radix/pagination"),
  "popover": () => import("@/content/examples/overrides/radix/popover"),
  "progress": () => import("@/content/examples/.generated/radix/progress"),
  "radio-group": () => import("@/content/examples/.generated/radix/radio-group"),
  "resizable": () => import("@/content/examples/.generated/radix/resizable"),
  "scroll-area": () => import("@/content/examples/.generated/radix/scroll-area"),
  "select": () => import("@/content/examples/.generated/radix/select"),
  "separator": () => import("@/content/examples/.generated/radix/separator"),
  "sheet": () => import("@/content/examples/overrides/radix/sheet"),
  "skeleton": () => import("@/content/examples/.generated/radix/skeleton"),
  "slider": () => import("@/content/examples/.generated/radix/slider"),
  "spinner": () => import("@/content/examples/.generated/radix/spinner"),
  "switch": () => import("@/content/examples/.generated/radix/switch"),
  "table": () => import("@/content/examples/.generated/radix/table"),
  "tabs": () => import("@/content/examples/.generated/radix/tabs"),
  "textarea": () => import("@/content/examples/.generated/radix/textarea"),
  "toggle": () => import("@/content/examples/.generated/radix/toggle"),
  "toggle-group": () => import("@/content/examples/overrides/radix/toggle-group"),
  "tooltip": () => import("@/content/examples/overrides/radix/tooltip"),
}
