/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples and
 * app/content/examples/overrides/base — do not edit. Change those sources
 * and re-run `pnpm sync:gallery`.
 *
 * One lazy loader per example for the base base. Where a hand-written
 * override exists for this base it wins; every other entry points at the
 * generated copy of the shared source, whose import specifiers were
 * rewritten to this base's component tree. Resolution happened here, in the
 * generator — consumers call the loader and get both the preview and the
 * usage snippet from the one module.
 */

import type { Example } from "@/content/example"

export const EXAMPLES: Record<string, () => Promise<Example>> = {
  "accordion": () => import("@/content/examples/overrides/base/accordion"),
  "alert": () => import("@/content/examples/.generated/base/alert"),
  "alert-dialog": () => import("@/content/examples/overrides/base/alert-dialog"),
  "aspect-ratio": () => import("@/content/examples/.generated/base/aspect-ratio"),
  "attachment": () => import("@/content/examples/.generated/base/attachment"),
  "avatar": () => import("@/content/examples/.generated/base/avatar"),
  "badge": () => import("@/content/examples/.generated/base/badge"),
  "breadcrumb": () => import("@/content/examples/.generated/base/breadcrumb"),
  "button": () => import("@/content/examples/.generated/base/button"),
  "button-group": () => import("@/content/examples/.generated/base/button-group"),
  "calendar": () => import("@/content/examples/.generated/base/calendar"),
  "card": () => import("@/content/examples/.generated/base/card"),
  "carousel": () => import("@/content/examples/.generated/base/carousel"),
  "chart": () => import("@/content/examples/.generated/base/chart"),
  "checkbox": () => import("@/content/examples/.generated/base/checkbox"),
  "collapsible": () => import("@/content/examples/overrides/base/collapsible"),
  "combobox": () => import("@/content/examples/overrides/base/combobox"),
  "command": () => import("@/content/examples/.generated/base/command"),
  "data-table": () => import("@/content/examples/.generated/base/data-table"),
  "dialog": () => import("@/content/examples/overrides/base/dialog"),
  "direction": () => import("@/content/examples/overrides/base/direction"),
  "dropdown-menu": () => import("@/content/examples/overrides/base/dropdown-menu"),
  "empty": () => import("@/content/examples/.generated/base/empty"),
  "field": () => import("@/content/examples/.generated/base/field"),
  "hover-card": () => import("@/content/examples/overrides/base/hover-card"),
  "input": () => import("@/content/examples/.generated/base/input"),
  "input-group": () => import("@/content/examples/.generated/base/input-group"),
  "input-otp": () => import("@/content/examples/overrides/base/input-otp"),
  "item": () => import("@/content/examples/.generated/base/item"),
  "kbd": () => import("@/content/examples/.generated/base/kbd"),
  "label": () => import("@/content/examples/.generated/base/label"),
  "native-select": () => import("@/content/examples/.generated/base/native-select"),
  "navigation-menu": () => import("@/content/examples/.generated/base/navigation-menu"),
  "pagination": () => import("@/content/examples/.generated/base/pagination"),
  "popover": () => import("@/content/examples/overrides/base/popover"),
  "progress": () => import("@/content/examples/.generated/base/progress"),
  "radio-group": () => import("@/content/examples/.generated/base/radio-group"),
  "resizable": () => import("@/content/examples/.generated/base/resizable"),
  "scroll-area": () => import("@/content/examples/.generated/base/scroll-area"),
  "select": () => import("@/content/examples/.generated/base/select"),
  "separator": () => import("@/content/examples/.generated/base/separator"),
  "sheet": () => import("@/content/examples/overrides/base/sheet"),
  "skeleton": () => import("@/content/examples/.generated/base/skeleton"),
  "slider": () => import("@/content/examples/.generated/base/slider"),
  "spinner": () => import("@/content/examples/.generated/base/spinner"),
  "switch": () => import("@/content/examples/.generated/base/switch"),
  "table": () => import("@/content/examples/.generated/base/table"),
  "tabs": () => import("@/content/examples/.generated/base/tabs"),
  "textarea": () => import("@/content/examples/.generated/base/textarea"),
  "toggle": () => import("@/content/examples/.generated/base/toggle"),
  "toggle-group": () => import("@/content/examples/overrides/base/toggle-group"),
  "tooltip": () => import("@/content/examples/overrides/base/tooltip"),
}
