/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/alert.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("base") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * alert example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx agent-ui add`.
 */

import type * as React from "react"

import { Alert, AlertDescription, AlertTitle } from "@/components/base/ui/alert"

export function Preview(): React.JSX.Element {
  return (
    <Alert variant="destructive" className="max-w-sm">
      <AlertTitle>Payment failed</AlertTitle>
      <AlertDescription>
        Your card was declined. Try another payment method.
      </AlertDescription>
    </Alert>
  )
}

export const usage = `<Alert variant="destructive">
  <AlertTitle>Payment failed</AlertTitle>
  <AlertDescription>Your card was declined.</AlertDescription>
</Alert>`
