/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/data-table.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("base") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * data-table example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx agent-ui add`.
 */

import type * as React from "react"

import { DataTable, type DataTableColumn } from "@/components/base/ui/data-table"

interface PreviewRow {
  id: string
  name: string
  role: string
  joined: string
}

const PREVIEW_ROWS: PreviewRow[] = [
  { id: "u1", name: "Ada Lovelace", role: "Engineer", joined: "2024-01" },
  { id: "u2", name: "Alan Turing", role: "Researcher", joined: "2023-11" },
  { id: "u3", name: "Grace Hopper", role: "Lead", joined: "2022-06" },
]

const PREVIEW_COLUMNS: DataTableColumn<PreviewRow>[] = [
  { id: "id", header: "ID", accessor: (r) => r.id },
  { id: "name", header: "Name", accessor: (r) => r.name },
  { id: "role", header: "Role", accessor: (r) => r.role },
  { id: "joined", header: "Joined", accessor: (r) => r.joined },
]

export function Preview(): React.JSX.Element {
  return (
    <DataTable
      data={PREVIEW_ROWS}
      columns={PREVIEW_COLUMNS}
      getRowId={(r) => r.id}
      agent={{ id: "preview-data-table", label: "Preview data table" }}
      pageSize={5}
    />
  )
}

export const usage = `<DataTable
  data={orders}
  columns={columns}
  getRowId={(order) => order.id}
  agent={{ id: "orders", label: "Orders" }}
/>`
