/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/field.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("base") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * field example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx agent-ui add`.
 */

import type * as React from "react"

import { Field, FieldDescription, FieldLabel } from "@/components/base/ui/field"
import { Input } from "@/components/base/ui/input"

export function Preview(): React.JSX.Element {
  return (
    <Field className="max-w-xs">
      <FieldLabel htmlFor="preview-field">Display name</FieldLabel>
      <Input id="preview-field" placeholder="Ada Lovelace" />
      <FieldDescription>Shown on your profile and in comments.</FieldDescription>
    </Field>
  )
}

export const usage = `<Field>
  <FieldLabel htmlFor="display-name">Display name</FieldLabel>
  <Input id="display-name" placeholder="Ada Lovelace" />
  <FieldDescription>Shown on your profile.</FieldDescription>
</Field>`
