/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/input.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("base") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * input example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx duz-ui add`.
 */

import type * as React from "react"

import { Input } from "@/components/base/ui/input"
import { Label } from "@/components/base/ui/label"

export function Preview(): React.JSX.Element {
  return (
    <div className="space-y-1.5">
      <Label htmlFor="preview-input">Email</Label>
      <Input
        id="preview-input"
        type="email"
        placeholder="you@example.com"
        agent={{ id: "preview-input", label: "Preview input" }}
      />
    </div>
  )
}

export const usage = `<Input
  type="email"
  placeholder="you@example.com"
  agent={{ id: "contact-email", label: "Contact email" }}
/>`
