/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/label.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("base") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * label example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx duz-ui add`.
 */

import type * as React from "react"

import { Label } from "@/components/base/ui/label"

export function Preview(): React.JSX.Element {
  return (
    <Label htmlFor="label-demo">Form label</Label>
  )
}

export const usage = `<Label htmlFor="email">Email</Label>`
