/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/switch.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("base") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * switch example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx duz-ui add`.
 */

import * as React from "react"

import { Label } from "@/components/base/ui/label"
import { Switch } from "@/components/base/ui/switch"

export function Preview(): React.JSX.Element {
  const [checked, setChecked] = React.useState<boolean>(false)
  return (
    <div className="flex items-center gap-3">
      <Switch
        id="preview-switch"
        checked={checked}
        onCheckedChange={setChecked}
        agent={{ id: "preview-switch", label: "Preview switch" }}
      />
      <Label htmlFor="preview-switch">Enable notifications</Label>
    </div>
  )
}

export const usage = `<div className="flex items-center gap-3">
  <Switch
    id="notifications"
    checked={enabled}
    onCheckedChange={setEnabled}
    agent={{ id: "notifications", label: "Enable notifications" }}
  />
  <Label htmlFor="notifications">Enable notifications</Label>
</div>`
