/**
 * Generated by scripts/sync-gallery.mjs from app/content/examples/textarea.tsx —
 * do not edit. Change the source file and re-run `pnpm sync:gallery`.
 *
 * Only the import specifiers are rewritten, to this file's base
 * ("base") component tree; everything else is byte-identical to the
 * source.
 */

/**
 * textarea example — one shared source for both bases. Its imports point at
 * the radix tree, which scripts/sync-gallery.mjs rewrites per base, so
 * every base renders the same source a user gets after `npx agent-ui add`.
 */

import type * as React from "react"

import { Label } from "@/components/base/ui/label"
import { Textarea } from "@/components/base/ui/textarea"

export function Preview(): React.JSX.Element {
  return (
    <div className="space-y-1.5">
      <Label htmlFor="preview-textarea">Bio</Label>
      <Textarea
        id="preview-textarea"
        placeholder="Tell us about yourself"
        agent={{ id: "preview-textarea", label: "Preview textarea" }}
      />
    </div>
  )
}

export const usage = `<div className="space-y-1.5">
  <Label htmlFor="bio">Bio</Label>
  <Textarea
    id="bio"
    placeholder="Tell us about yourself"
    agent={{ id: "bio", label: "Bio" }}
  />
</div>`
