/**
 * Agent UI — stock fingerprint generator.
 *
 * A developer script (not run at install time) that reads every vendored stock
 * source in `packages/cli/stock/<base>/*.tsx`, computes a
 * structural fingerprint for each, and writes `packages/cli/src/codemods/stock-fingerprints.ts`
 * as a per-base record: base -> component name -> hashes.
 *
 * Run with `pnpm --filter agent-ui generate:fingerprints`.
 *
 * The repository root is resolved from this script's location, not from
 * `process.cwd()`, so the script works regardless of the working directory.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { fingerprintSource } from "../src/codemods/fingerprint.js"
import { REGISTRY_BASES } from "../src/registry/client.js"

const __dirname = dirname(fileURLToPath(import.meta.url))
const stockDir = join(__dirname, "../stock")
const outputFile = join(__dirname, "../src/codemods/stock-fingerprints.ts")

const fingerprints: Record<string, Record<string, string[]>> = {}
for (const base of REGISTRY_BASES) {
  const baseDir = join(stockDir, base)
  const files = readdirSync(baseDir)
    .filter((file) => file.endsWith(".tsx"))
    .sort()

  const perBase: Record<string, string[]> = {}
  for (const file of files) {
    const name = file.replace(/\.tsx$/, "")
    const source = readFileSync(join(baseDir, file), "utf8")
    perBase[name] = [fingerprintSource(source)]
  }
  fingerprints[base] = perBase
}

const body = JSON.stringify(fingerprints, null, 2)

const content = `/**
 * Generated by \`packages/cli/scripts/generate-stock-fingerprints.ts\` from the
 * vendored stock sources in \`packages/cli/stock/<base>/\`. Do not
 * edit by hand; regenerate with \`pnpm --filter agent-ui generate:fingerprints\`.
 */

export const STOCK_FINGERPRINTS: Record<string, Record<string, string[]>> = ${body}
`

writeFileSync(outputFile, content, "utf8")
console.log(`Wrote ${outputFile}`)
