/**
 * Agent UI — stock fingerprint generator.
 *
 * A developer script (not run at install time) that reads every vendored stock
 * source in `docs/internal/reference/shadcn/*.tsx`, computes a structural
 * fingerprint for each, and writes `packages/cli/src/codemods/stock-fingerprints.ts`.
 *
 * Run with `pnpm --filter agent-ui generate:fingerprints`.
 *
 * The repository root is resolved from this script's location, not from
 * `process.cwd()`, so the script works regardless of the working directory.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { fingerprintSource } from "../src/codemods/fingerprint.js"

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, "../../..")
const stockDir = join(repoRoot, "docs/internal/reference/shadcn")
const outputFile = join(repoRoot, "packages/cli/src/codemods/stock-fingerprints.ts")

const files = readdirSync(stockDir)
  .filter((file) => file.endsWith(".tsx"))
  .sort()

const fingerprints: Record<string, string[]> = {}
for (const file of files) {
  const name = file.replace(/\.tsx$/, "")
  const source = readFileSync(join(stockDir, file), "utf8")
  fingerprints[name] = [fingerprintSource(source)]
}

const body = JSON.stringify(fingerprints, null, 2)

const content = `/**
 * Generated by \`packages/cli/scripts/generate-stock-fingerprints.ts\` from the
 * vendored stock sources in \`docs/internal/reference/shadcn/\`. Do not edit by
 * hand; regenerate with \`pnpm --filter agent-ui generate:fingerprints\`.
 */

export const STOCK_FINGERPRINTS: Record<string, string[]> = ${body}
`

writeFileSync(outputFile, content, "utf8")
console.log(`Wrote ${outputFile}`)
