/**
 * Generated by `packages/cli/scripts/generate-stock-fingerprints.ts` from the
 * vendored stock sources in `packages/cli/stock/<base>/`. Do not
 * edit by hand; regenerate with `pnpm --filter duz-ui generate:fingerprints`.
 */

export const STOCK_FINGERPRINTS: Record<string, Record<string, string[]>> = {
  "base": {
    "accordion": [
      "cc5bc7d181cbb9ecb23c446797dcb47d6c98e7f02cdb577250699178d65ba134"
    ],
    "alert-dialog": [
      "4afa3093a6cd70a2545eaf1f7efbea0169deab49e3365f3b480497519185340e"
    ],
    "button": [
      "6e436c4f68e412f13225a5562d5627f7b707d578fc42747c3a575e3686a0439a"
    ],
    "card": [
      "97f69f78bc0deea5f2747d5bcb3211a4ce53caf4a911f9f06e384cdac489c027"
    ],
    "chart": [
      "10268d1770d53cc0a5eae17153a11013477629134fca2ee6ba526de3ce335913"
    ],
    "checkbox": [
      "f69ce37fceb21ef40875e7069d9f2d5c72a3038be40882d51f58881d6c06aa8b"
    ],
    "collapsible": [
      "e16c94231e7343bd56b4aa8f0d3cfd5464e73fca581a62b481eb266e3fbec223"
    ],
    "command": [
      "c15c0ec5651b6fa4cf63f1b64e8b2d7cd76f02d03e994ed4049e5063fc3237b2"
    ],
    "context-menu": [
      "dbed5db45172f5d17265fbc34647b148b4f754425c44c90074641ee85b23dbe7"
    ],
    "dialog": [
      "000221754d10db1fc062b5ec935e28bc1761719c8dabfe5b5a931137d6526fda"
    ],
    "drawer": [
      "98e96981a73917e70bb75f126430b5fcfe130abcc36147e0e6e0134b083cf7ff"
    ],
    "dropdown-menu": [
      "d6f874df88673c38293a8aca6960ab3ade48497fc3ee43353d62681b27c0ceb8"
    ],
    "hover-card": [
      "c70bf5f5154edf61e90684e80c792ea275ff92e29a42c47432f3a3096e196a78"
    ],
    "input-otp": [
      "d6123465596a811baed99087649ce913b332487554eb9b2c6cbbecc40e730d62"
    ],
    "input": [
      "0987ebaf66efab5f62428371f62e7396a7eb3c21b50612a129f4b4879438c4b3"
    ],
    "label": [
      "75b5c5f02f536f36bd71f43c873d606735d3a22379e5f4fafa7511a1fcb8c2a1"
    ],
    "menubar": [
      "a61c2357d61f063416a1c92f133752f06f6748161074fce574fdae860eaa3c2a"
    ],
    "pagination": [
      "e909a7f3ed3066a00bba308119c4673c1edfa495c2815042c008bedc5f08ed50"
    ],
    "popover": [
      "95684edb26339d275c1c3f5f04a7737dd5f19481ee13a6cb8790847433063848"
    ],
    "radio-group": [
      "f4aeb40c7c926f6f5abd393fd11bbb97d172d5a9f2cc8b699e794d0b647dc894"
    ],
    "select": [
      "0843fc7b2cdfe12fe606f41e12e14b878e71eefc4abd03726ad5631855864e7a"
    ],
    "separator": [
      "e8bcb95863ff754a6b3105670ca65c59ea68e444175d1efc5fc07792f2dadc90"
    ],
    "sheet": [
      "1ef2de1ace9ff82383a95133c0892c0533a48db18c8b618b03ae1e7282a7c153"
    ],
    "sidebar": [
      "6d3555dc2e29aad57ceb31f2801cb091826d66d1935c29959b9755203c9aa875"
    ],
    "skeleton": [
      "2ef7fa142f3d6373c528cb9abd93883493a958ced9dccc5a8d0acd9e7246f97c"
    ],
    "slider": [
      "75e9a95914351b28647a95dcd767902e8b14272496e8eab90d5d32d650f15280"
    ],
    "sonner": [
      "32c4ebf851c67f6001fbd27a7307351b11d4aeef6d31fb120a6e1102b5a14b4f"
    ],
    "switch": [
      "9edc785e78bd6dc0654920987d8d315ceadce49b8f825ba95847545dc467a9a4"
    ],
    "table": [
      "5dbe7f4f1ace10ed04c9b6e5c534b36a32de192f8448963729bd287854957992"
    ],
    "tabs": [
      "eec2edc9ef9bb7134436b91f3498d9bc45811e1366bd45d49a4c8e5a0bfaec24"
    ],
    "textarea": [
      "a3369f4fd0c35d35f36d97ce9245bf96811af68c2ceb1f3b0762426324f8174d"
    ],
    "toggle": [
      "d720e399b3c3de31e3e8f1eba1ca9daf1b494a88cbd2649cc79b76d60b5f2f4c"
    ],
    "tooltip": [
      "2d9c148484d30693b2e2eaf59173305ec4c83d4e3d9657f88d73ad960ef0e306"
    ]
  },
  "radix": {
    "accordion": [
      "1e5023f1396d824820b156ee1c7616c8f18c85f024ab7f5e13f1a1adad14c88e"
    ],
    "alert-dialog": [
      "badc93be08bda16b229d8e085ed17b41ba17184bd9e7b09fa853f474af4020b9"
    ],
    "button": [
      "a38223148f93974bbdf8b148037f47e76863a587030a4ef012265a9a3cf79284"
    ],
    "card": [
      "97f69f78bc0deea5f2747d5bcb3211a4ce53caf4a911f9f06e384cdac489c027"
    ],
    "chart": [
      "6fcfab3480b9f2fe55f9b2b3de0c176b8b40fb1e05fc13966566393f9cd37b56"
    ],
    "checkbox": [
      "0388888c89caea7c18f710775657531412e13d32634ca6afd79dbc143b8a2a23"
    ],
    "collapsible": [
      "e3fa1e37ee944c85da913968d096cae863b908838804371d6d1ee94af7dc00c2"
    ],
    "command": [
      "06be632a74cdf9868e4bc6a618a62099de9d626c3da4dd185c3f708e3693599a"
    ],
    "context-menu": [
      "01042320fc77c5310972605e69ed0348c5d7e993718c15df5ff749c3e6391c7b"
    ],
    "dialog": [
      "3715d8d640364a0a3853ed3d88a39b72f0dc3b5a4ff337c0899f436cdb99afa0"
    ],
    "drawer": [
      "7ed7b4b644c5c80bb60e2cd314a42f570018a542e7dc6af12e5c69f351579041"
    ],
    "dropdown-menu": [
      "2fe4177c4095514cc18ae4223018db857cf55b952775ac5b7cda8b62bdc61630"
    ],
    "hover-card": [
      "66cad6eba90a11ea137b3dd28b33b20fedfb550f95e28e8cfec7a643096bac8f"
    ],
    "input-otp": [
      "ae1dc0761812107f7f69197f1ffad1096221b0360f31047acd83847ab6ecd521"
    ],
    "input": [
      "8a27ea9e35ce088cd6e60b369b949de9cd16e8f39e4b449287e10a3f7d28e1d0"
    ],
    "label": [
      "6fa2849dcebe1d76f608212f84adbd885a2bd69c0ebbe533108e7e6dbcb36f81"
    ],
    "menubar": [
      "946074e77b15906d545211f2aa3214cc9c8fed939d3d2518da6a9cddf5b3417c"
    ],
    "pagination": [
      "6f900f3ab9c147b043730c32a14cbb07ae7cc12104ee3c6633f1da2069d07203"
    ],
    "popover": [
      "2ebfea05946a2162c497df7651ae045d779df024b3249523e1403d9becb08568"
    ],
    "radio-group": [
      "8b676ed3183d65c1a7d17cd7e64cc6f56592358a09dc2312f7557f6d6803deb3"
    ],
    "select": [
      "ee013964c28199b8a777f8d9075bb8bb779a628f3795c134e3b1f35f0bd5cfa6"
    ],
    "separator": [
      "80dc0b46396fd18521378d512d1933c8da48e6877ed48a33c286bd2fb484bfc8"
    ],
    "sheet": [
      "6097b37018782e5adbe4f7adc23ba4d81ad6b0b3fc5948a87f91903104ce6843"
    ],
    "sidebar": [
      "be0f579de3d8b105f5310cd73758530e4268203a61d5a167fe80d3957140cae2"
    ],
    "skeleton": [
      "c043cbb127469bdb4d69d676dbb29ab230edee147c3d87b067af91fa76821b7e"
    ],
    "slider": [
      "e55a5dc06388df4cfb882fb2ad6c59ccd8af78641f7b55153041139bd597b86f"
    ],
    "sonner": [
      "32c4ebf851c67f6001fbd27a7307351b11d4aeef6d31fb120a6e1102b5a14b4f"
    ],
    "switch": [
      "85e754ec1e197b27d0288df9ac83b2ae66c5798f6d9c3f96585f279e5bde4a21"
    ],
    "table": [
      "bd162fa9723f26efe664c0845a74a8c55359fbb13ed3a964bc481d33646feb96"
    ],
    "tabs": [
      "59a2fe29d086fd1fd9cc4a87a2dd87d4861b54dded124c790845077a35038ebb"
    ],
    "textarea": [
      "4bb9151be33a65ad20130b8f95bb0d3efe06cc58537daae46740536ad6171300"
    ],
    "toggle": [
      "d17c4fe62536174c6ff18d6321a59ca9108a89d787dd2f92441a813553a36cf9"
    ],
    "tooltip": [
      "db2756995e710e269e052872b895a8ef6e3864eeb7a142f88cdc379cb4e946dc"
    ]
  }
}
