/**
 * Generated by `packages/cli/scripts/generate-stock-fingerprints.ts` from the
 * vendored stock sources in `docs/internal/reference/shadcn/`. Do not edit by
 * hand; regenerate with `pnpm --filter agent-ui generate:fingerprints`.
 */

export const STOCK_FINGERPRINTS: Record<string, string[]> = {
  "button": [
    "a38223148f93974bbdf8b148037f47e76863a587030a4ef012265a9a3cf79284"
  ],
  "checkbox": [
    "0388888c89caea7c18f710775657531412e13d32634ca6afd79dbc143b8a2a23"
  ],
  "dialog": [
    "3715d8d640364a0a3853ed3d88a39b72f0dc3b5a4ff337c0899f436cdb99afa0"
  ],
  "input": [
    "8a27ea9e35ce088cd6e60b369b949de9cd16e8f39e4b449287e10a3f7d28e1d0"
  ],
  "label": [
    "6fa2849dcebe1d76f608212f84adbd885a2bd69c0ebbe533108e7e6dbcb36f81"
  ],
  "select": [
    "ee013964c28199b8a777f8d9075bb8bb779a628f3795c134e3b1f35f0bd5cfa6"
  ],
  "table": [
    "bd162fa9723f26efe664c0845a74a8c55359fbb13ed3a964bc481d33646feb96"
  ],
  "tabs": [
    "59a2fe29d086fd1fd9cc4a87a2dd87d4861b54dded124c790845077a35038ebb"
  ]
}
